title: Parv Pratap Singh
logo: assets/img/1234.png
description: I am a data scientist with experience in application development as well, currently driving sustainable technology solutions at Kinesis IT Solutions. Drawing from my personal experiences and expertise in AI and machine learning, I am passionate about advancing healthcare by developing data-driven solutions that improve diagnosis and personalises treatment.
show_downloads: true
theme: jekyll-theme-minimal
